### ISSUE TITLE
Alexa responds, Magic Mirror does not

### ISSUE THREAD

**Issue by UJamil** [joanaz/MMM-MirrorMirrorOnTheWall#9]
I have [AlexaPi](https://github.com/alexa-pi/AlexaPi) running on my Raspberry Pi 3, as well as the Magic Mirror. I have followed both tutorials and setup the Alexa skill and module. The Alexa is definitely working, for example, I can say "Alexa, ..., 'on the wall', ... , hide [calendar, etc.]" and Alexa says "hiding calendar". However, I have tried to show/hide specific modules and show/hide all modules, but it does not seem Magic Mirror is showing/hiding the modules. 

I do get this error, after running Magic Mirror:

> Whoops! There was an uncaught exception...
Error: Invalid connect options supplied.
    at new DeviceClient (/home/pi/MagicMirror/modules/MMM-MirrorMirrorOnTheWall/node_modules/aws-iot-device-sdk/device/index.js:406:13)
    at Object.DeviceClient [as device] (/home/pi/MagicMirror/modules/MMM-MirrorMirrorOnTheWall/node_modules/aws-iot-device-sdk/device/index.js:201:14)
    at Object.app.setup (/home/pi/MagicMirror/modules/MMM-MirrorMirrorOnTheWall/MirrorMirror.js:12:23)
    at Class.alexa_start (/home/pi/MagicMirror/modules/MMM-MirrorMirrorOnTheWall/node_helper.js:12:18)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-MirrorMirrorOnTheWall/node_helper.js:35:12)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:103:11)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:514:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

Also:
I'm not quite sure what the "replace paths" in the MirrorMirror.js meant, but I changed them to:
`keyPath: "/home/pi/MagicMirror/modules/MMM-MirrorMirrorOnTheWall/certs",`
`certPath: "/home/pi/MagicMirror/modules/MMM-MirrorMirrorOnTheWall/certs",`
`caPath: "/home/pi/MagicMirror/modules/MMM-MirrorMirrorOnTheWall/certs",`

**Comment by UJamil** [comment]
Nevermind: solved by changing the above paths to
`keyPath: __dirname + "/certs/MagicMirror.private.key",`
`certPath: __dirname + "/certs/MagicMirror.cert.pem",`
`caPath: __dirname + "/certs/root-CA.crt",`

**Comment by dugemaniac** [comment]
hi there, sorry im reopen the issue, as im having the same problem. i have already install alexa skill, 
and testing it, and it seem to work, here is the example
![2017-09-27_14-05-43](https://user-images.githubusercontent.com/32019927/30900154-0b037562-a38d-11e7-8c6b-fd5667e28596.jpg)

i talked, and mirrormirror respond "helllo my queen ..." but nothing is shown on the magic mirror.
i've already copy the cert file into my modules/MMM-MirrorMirrorOnTheWall/certs
edit the JS file as suggested by @UJamil 

In config.js i put
{
    module: 'MMM-MirrorMirrorOnTheWall',
    position: "middle_center",
    config: {}
}
Is there any part i missed? kindly help. Thank you
